[package]
name = "pam-random"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam-bindings = "0.1.1"
rand = "0.9.0-alpha.0"
